name: Build & Deploy Flutter Web

on:
  push:
    branches:
      - main   # change if your main branch is different

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Build Flutter web
      - run: flutter pub get
      - run: flutter build web --release --base-href "/<repo-name>/"

      # Deploy to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
